set(_AMENT_PACKAGE_NAME "pepper_robot_description")
set(pepper_robot_description_VERSION "1.0.0")
set(pepper_robot_description_MAINTAINER "Hiba Sekkat <h.sekkat@ueuromed.org>")
set(pepper_robot_description_BUILD_DEPENDS )
set(pepper_robot_description_BUILDTOOL_DEPENDS "ament_cmake")
set(pepper_robot_description_BUILD_EXPORT_DEPENDS )
set(pepper_robot_description_BUILDTOOL_EXPORT_DEPENDS )
set(pepper_robot_description_EXEC_DEPENDS "joint_state_publisher_gui" "robot_state_publisher" "ros_ign_gazebo" "rviz2" "urdf" "xacro")
set(pepper_robot_description_TEST_DEPENDS )
set(pepper_robot_description_GROUP_DEPENDS )
set(pepper_robot_description_MEMBER_OF_GROUPS )
set(pepper_robot_description_DEPRECATED "")
set(pepper_robot_description_EXPORT_TAGS)
list(APPEND pepper_robot_description_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
