set(_AMENT_PACKAGE_NAME "pepper_robot_ign")
set(pepper_robot_ign_VERSION "1.0.0")
set(pepper_robot_ign_MAINTAINER "Hiba Sekkat <h.sekkat@ueuromed.org>")
set(pepper_robot_ign_BUILD_DEPENDS )
set(pepper_robot_ign_BUILDTOOL_DEPENDS "ament_cmake")
set(pepper_robot_ign_BUILD_EXPORT_DEPENDS )
set(pepper_robot_ign_BUILDTOOL_EXPORT_DEPENDS )
set(pepper_robot_ign_EXEC_DEPENDS "pepper_robot_description" "pepper_robot_moveit_config" "ign_ros2_control" "ros_ign_bridge" "ros_ign_gazebo" "rviz2")
set(pepper_robot_ign_TEST_DEPENDS )
set(pepper_robot_ign_GROUP_DEPENDS )
set(pepper_robot_ign_MEMBER_OF_GROUPS )
set(pepper_robot_ign_DEPRECATED "")
set(pepper_robot_ign_EXPORT_TAGS)
list(APPEND pepper_robot_ign_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
