initial_joint_positions:
  HeadPitch: -0.2
  HeadYaw: 0.0
  LElbowRoll: -0.52
  LElbowYaw: -1.22
  LFinger11: 0.1
  LFinger12: 0.1
  LFinger13: 0.1
  LFinger21: 0.1
  LFinger22: 0.1
  LFinger23: 0.1
  LFinger31: 0.1
  LFinger32: 0.1
  LFinger33: 0.1
  LFinger41: 0.1
  LFinger42: 0.1
  LFinger43: 0.1
  LHand: 0.5
  LShoulderPitch: 1.77
  LShoulderRoll: 0.17
  LThumb1: 0.1
  LThumb2: 0.1
  LWristYaw: 0.0
  RElbowRoll: 0.17
  RElbowYaw: 1.22
  RFinger11: 0.1
  RFinger12: 0.1
  RFinger13: 0.1
  RFinger21: 0.1
  RFinger22: 0.1
  RFinger23: 0.1
  RFinger31: 0.1
  RFinger32: 0.1
  RFinger33: 0.1
  RFinger41: 0.1
  RFinger42: 0.1
  RFinger43: 0.1
  RHand: 0.5
  RShoulderPitch: 1.77
  RShoulderRoll: -0.17
  RThumb1: 0.1
  RThumb2: 0.1
  RWristYaw: 0.0
  KneePitch: 0.0
  HipPitch: 0.0
  HipRoll: 0.0
