controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    torso_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

head_controller:
  ros__parameters:
    joints:
      - HeadYaw
      - HeadPitch
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

torso_controller:
  ros__parameters:
    joints:
      - HipRoll
      - HipPitch
      - KneePitch
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

left_arm_controller:
  ros__parameters:
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

left_hand_controller:
  ros__parameters:
    joints:
      - LHand
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

right_arm_controller:
  ros__parameters:
    joints:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

right_hand_controller:
  ros__parameters:
    joints:
      - RHand
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
