controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller

    gripper_trajectory_controller:
      type: joint_trajectory_controller

joint_trajectory_controller:
  ros__parameters:
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
      - LHand
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_trajectory_controller:
  ros__parameters:
    joints:
      - LFinger11
      - LFinger12
      - LFinger13
      - LFinger21
      - LFinger22
      - LFinger23
      - LFinger31
      - LFinger32
      - LFinger33
      - LFinger41
      - LFinger42
      - LFinger43
      - LThumb1
      - LThumb2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity