 controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

 joint_trajectory_controller:
  ros__parameters:
    - name: left_arm
        joints:
          - LShoulderPitch
          - LShoulderRoll
          - LElbowYaw
          - LElbowRoll
          - LWristYaw
    - name: right_arm
        joints:
          - RShoulderPitch
          - RShoulderRoll
          - RElbowYaw
          - RElbowRoll
          - RWristYaw
    - name: Head
        joints:
          - HeadYaw
          - HeadPitch
    - name: Pelvis
        joints:
          - HipRoll
          - HipPitch
          - KneePitch
    - name: left_hand
        joints:
          - LHand
    - name: right_hand
        joints:
          - RHand
    command_interfaces:
          - effort
    state_interfaces:
          - position
          - velocity

