controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw
      - HeadYaw
      - HeadPitch
      - HipRoll
      - HipPitch
      - KneePitch
      - LHand
      - RHand
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      LShoulderPitch:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      LShoulderRoll:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      LElbowYaw:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      LElbowRoll:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      LWristYaw:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      RShoulderPitch:
        p: 500
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      RShoulderRoll:
        p: 500
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      RElbowYaw:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      RElbowRoll:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      HeadYaw:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      HeadPitch:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      HipRoll:
        p: 1000
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      HipPitch:
        p: 1000
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      KneePitch:
        p: 1000
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LHand:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      RHand:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
gripper_trajectory_controller:
  ros__parameters:
    joints:
      - LFinger11
      - LFinger12
      - LFinger13
      - RFinger11
      - RFinger12
      - RFinger13
      - LFinger21
      - LFinger22
      - LFinger23
      - RFinger21
      - RFinger22
      - RFinger23
      - LFinger31
      - LFinger32
      - LFinger33
      - RFinger31
      - RFinger32
      - RFinger33
      - LFinger41
      - LFinger42
      - LFinger43
      - RFinger41
      - RFinger42
      - RFinger43
      - LThumb1
      - RThumb1
      - LThumb2
      - RThumb2

    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      LFinger11:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      LFinger12:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      LFinger13:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      RFinger11:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      RFinger12:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      RFinger13:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      LFinger21:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      LFinger22:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      LFinger23:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      RFinger21:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      RFinger22:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      RFinger23:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      LFinger31:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      LFinger32:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      LFinger33:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      RFinger31:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      RFinger32:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      RFinger33:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      LFinger41:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      LFinger42:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      LFinger43:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      RFinger41:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      RFinger42:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      RFinger43:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      LThumb1:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      RThumb1:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      LThumb2:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0
      RThumb2:
        p: 1500
        i: 5.0
        d: 50.0
        i_clamp: 10.0