controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller

    gripper_trajectory_controller:
      type: joint_trajectory_controller

joint_trajectory_controller:
  ros__parameters:
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
      - LHand
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      LShoulderPitch:
        p: 500
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LShoulderRoll:
        p: 500
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LElbowYaw:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LElbowRoll:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LWristYaw:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LHand:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
gripper_trajectory_controller:
  ros__parameters:
    joints:
      - LFinger11
      - LFinger12
      - LFinger13
      - LFinger21
      - LFinger22
      - LFinger23
      - LFinger31
      - LFinger32
      - LFinger33
      - LFinger41
      - LFinger42
      - LFinger43
      - LThumb1
      - LThumb2
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      LFinger11:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LFinger12:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LFinger13:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LFinger22:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LFinger23:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LFinger31:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LFinger32:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LFinger33:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LFinger41:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LFinger42:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LFinger43:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LThumb1:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LThumb2:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2