controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    left_arm:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
    right_arm:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw
    Head:
      - HeadYaw
      - HeadPitch
    Pelvis:
      - HipRoll
      - HipPitch
      - KneePitch
    left_hand:
      - LHand
    right_hand:
      - RHand
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

