controller_manager:
  ros__parameters:
    update_rate: 250
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw
      - HeadYaw
      - HeadPitch
      - HipRoll
      - HipPitch
      - KneePitch
      - LHand
      - RHand
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      LShoulderPitch:
        p: 1200.0
        i: 1.0
        d: 20.0
      LShoulderRoll:
        p: 1200.0
        i: 1.0
        d: 20.0
      LElbowYaw:
        p: 600.0
        i: 0.1
        d: 5.0
      LElbowRoll:
        p: 600.0
        i: 0.1
        d: 5.0
      LWristYaw:
        p: 400.0
        i: 0.1
        d: 2.0
      RShoulderPitch:
        p: 1200.0
        i: 1.0
        d: 20.0
      RShoulderRoll:
        p: 1200.0
        i: 1.0
        d: 20.0
      RElbowYaw:
        p: 600.0
        i: 0.1
        d: 5.0
      RElbowRoll:
        p: 600.0
        i: 0.1
        d: 5.0
      RWristYaw:
        p: 400.0
        i: 0.1
        d: 2.0
      HeadYaw:
        p: 400.0
        i: 0.1
        d: 2.0
      HeadPitch:
        p: 400.0
        i: 0.1
        d: 2.0
      HipRoll:
        p: 12000.0
        i: 10.0
        d: 100.0
      HipPitch:
        p: 18000.0
        i: 10.0
        d: 150.0
      KneePitch:
        p: 18000.0
        i: 10.0
        d: 150.0
      LHand:
        p: 100.0
        i: 0.1
        d: 1.0
      RHand:
        p: 100.0
        i: 0.1
        d: 1.0

gripper_trajectory_controller:
  ros__parameters:
    joints:
      - LFinger11
      - LFinger12
      - LFinger13
      - RFinger11
      - RFinger12
      - RFinger13
      - LFinger21
      - LFinger22
      - LFinger23
      - RFinger21
      - RFinger22
      - RFinger23
      - LFinger31
      - LFinger32
      - LFinger33
      - RFinger31
      - RFinger32
      - RFinger33
      - LFinger41
      - LFinger42
      - LFinger43
      - RFinger41
      - RFinger42
      - RFinger43
      - LThumb1
      - RThumb1
      - LThumb2
      - RThumb2
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      LFinger11: {p: 50.0, i: 0.0, d: 0.5}
      LFinger12: {p: 50.0, i: 0.0, d: 0.5}
      LFinger13: {p: 50.0, i: 0.0, d: 0.5}
      RFinger11: {p: 50.0, i: 0.0, d: 0.5}
      RFinger12: {p: 50.0, i: 0.0, d: 0.5}
      RFinger13: {p: 50.0, i: 0.0, d: 0.5}
      LFinger21: {p: 50.0, i: 0.0, d: 0.5}
      LFinger22: {p: 50.0, i: 0.0, d: 0.5}
      LFinger23: {p: 50.0, i: 0.0, d: 0.5}
      RFinger21: {p: 50.0, i: 0.0, d: 0.5}
      RFinger22: {p: 50.0, i: 0.0, d: 0.5}
      RFinger23: {p: 50.0, i: 0.0, d: 0.5}
      LFinger31: {p: 50.0, i: 0.0, d: 0.5}
      LFinger32: {p: 50.0, i: 0.0, d: 0.5}
      LFinger33: {p: 50.0, i: 0.0, d: 0.5}
      RFinger31: {p: 50.0, i: 0.0, d: 0.5}
      RFinger32: {p: 50.0, i: 0.0, d: 0.5}
      RFinger33: {p: 50.0, i: 0.0, d: 0.5}
      LFinger41: {p: 50.0, i: 0.0, d: 0.5}
      LFinger42: {p: 50.0, i: 0.0, d: 0.5}
      LFinger43: {p: 50.0, i: 0.0, d: 0.5}
      RFinger41: {p: 50.0, i: 0.0, d: 0.5}
      RFinger42: {p: 50.0, i: 0.0, d: 0.5}
      RFinger43: {p: 50.0, i: 0.0, d: 0.5}
      LThumb1: {p: 50.0, i: 0.0, d: 0.5}
      RThumb1: {p: 50.0, i: 0.0, d: 0.5}
      LThumb2: {p: 50.0, i: 0.0, d: 0.5}
      RThumb2: {p: 50.0, i: 0.0, d: 0.5}
