 controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

 joint_trajectory_controller:
  ros__parameters:
    - name: left_arm
        joints:
          - LShoulderPitch
          - LShoulderRoll
          - LElbowYaw
          - LElbowRoll
          - LWristYaw
    - name: right_arm
        joints:
          - RShoulderPitch
          - RShoulderRoll
          - RElbowYaw
          - RElbowRoll
          - RWristYaw
    - name: Head
        joints:
          - HeadYaw
          - HeadPitch
    - name: Pelvis
        joints:
          - HipRoll
          - HipPitch
          - KneePitch
    - name: left_hand
        joints:
          - LHand
    - name: right_hand
        joints:
          - RHand
    command_interfaces:
          - effort
    state_interfaces:
          - position
          - velocity
    gains:
      LWristYaw:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      RWristYaw:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LElbowRoll:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      RElbowRoll:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LElbowYaw:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      RElbowYaw:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LShoulderRoll:
        p: 500
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      RShoulderRoll:
        p: 500
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      LShoulderPitch:
        p: 500
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      RShoulderPitch:
        p: 500
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      HeadYaw:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      HeadPitch:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      HipRoll:
        p: 1000
        i: 0.1
        d: 5.0
        i_clamp: 0.2
      HipPitch:
        p: 1000
        i: 0.1
        d: 5.0
        i_clamp: 0.2
      KneePitch:
        p: 1000
        i: 0.1
        d: 5.0
        i_clamp: 0.2
      LHand:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
      RHand:
        p: 100
        i: 0.1
        d: 1.0
        i_clamp: 0.2
