 controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

 joint_trajectory_controller:
  ros__parameters:
    - name: left_arm
        joints:
          - LShoulderPitch
          - LShoulderRoll
          - LElbowYaw
          - LElbowRoll
          - LWristYaw
    - name: right_arm
        joints:
          - RShoulderPitch
          - RShoulderRoll
          - RElbowYaw
          - RElbowRoll
          - RWristYaw
    - name: Head
        joints:
          - HeadYaw
          - HeadPitch
    - name: Pelvis
        joints:
          - HipRoll
          - HipPitch
          - KneePitch
    - name: left_hand
        joints:
          - LHand
    - name: right_hand
        joints:
          - RHand
    command_interfaces:
          - effort
    state_interfaces:
          - position
          - velocity
  gains:
    LWristYaw:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    RWristYaw:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    LElbowRoll:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    RElbowRoll:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    LElbowYaw:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    RElbowYaw:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    LShoulderRoll:
      p: 500
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    RShoulderRoll:
      p: 500
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    LShoulderPitch:
      p: 500
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    RShoulderPitch:
      p: 500
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    HeadYaw:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    HeadPitch:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    HipRoll:
      p: 1000
      i: 0.1
      d: 5.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    HipPitch:
      p: 1000
      i: 0.1
      d: 5.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    KneePitch:
      p: 1000
      i: 0.1
      d: 5.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    LHand:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    RHand:
      p: 100
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
