# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  HeadPitch:
    has_velocity_limits: true
    max_velocity: 9.22756
    has_acceleration_limits: false
    max_acceleration: 0
  HeadYaw:
    has_velocity_limits: true
    max_velocity: 7.33998
    has_acceleration_limits: false
    max_acceleration: 0
  LElbowRoll:
    has_velocity_limits: true
    max_velocity: 9.22756
    has_acceleration_limits: false
    max_acceleration: 0
  LElbowYaw:
    has_velocity_limits: true
    max_velocity: 7.33998
    has_acceleration_limits: false
    max_acceleration: 0
  LFinger11:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  LFinger12:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  LFinger13:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  LFinger21:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  LFinger22:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  LFinger23:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  LFinger31:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  LFinger32:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  LFinger33:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  LFinger41:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  LFinger42:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  LFinger43:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  LHand:
    has_velocity_limits: true
    max_velocity: 12.56
    has_acceleration_limits: false
    max_acceleration: 0
  LShoulderPitch:
    has_velocity_limits: true
    max_velocity: 7.33998
    has_acceleration_limits: false
    max_acceleration: 0
  LShoulderRoll:
    has_velocity_limits: true
    max_velocity: 9.22756
    has_acceleration_limits: false
    max_acceleration: 0
  LThumb1:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  LThumb2:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  LWristYaw:
    has_velocity_limits: true
    max_velocity: 17.3835
    has_acceleration_limits: false
    max_acceleration: 0
  RElbowRoll:
    has_velocity_limits: true
    max_velocity: 9.22756
    has_acceleration_limits: false
    max_acceleration: 0
  RElbowYaw:
    has_velocity_limits: true
    max_velocity: 7.33998
    has_acceleration_limits: false
    max_acceleration: 0
  RFinger11:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RFinger12:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RFinger13:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RFinger21:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RFinger22:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RFinger23:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RFinger31:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RFinger32:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RFinger33:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RFinger41:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RFinger42:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RFinger43:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RHand:
    has_velocity_limits: true
    max_velocity: 12.56
    has_acceleration_limits: false
    max_acceleration: 0
  RShoulderPitch:
    has_velocity_limits: true
    max_velocity: 7.33998
    has_acceleration_limits: false
    max_acceleration: 0
  RShoulderRoll:
    has_velocity_limits: true
    max_velocity: 9.22756
    has_acceleration_limits: false
    max_acceleration: 0
  RThumb1:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RThumb2:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  RWristYaw:
    has_velocity_limits: true
    max_velocity: 17.3835
    has_acceleration_limits: false
    max_acceleration: 0