 controller_names:
  - joint_trajectory_controller
  - gripper_trajectory_controller
 # - gripper_action_controller

 joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - LShoulderPitch
    - LShoulderRoll
    - LElbowYaw
    - LElbowRoll
    - LWristYaw
    - LHand

 gripper_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - LFinger11
    - LFinger12
    - LFinger13
    - LFinger21
    - LFinger22
    - LFinger23
    - LFinger31
    - LFinger32
    - LFinger33
    - LFinger41
    - LFinger42
    - LFinger43
    - LThumb1
    - LThumb2

