 controller_names:
  - joint_trajectory_controller
  - gripper_trajectory_controller
  # - gripper_action_controller

 joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw

 gripper_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - LFinger11
      - LFinger12
      - LFinger13
      - RFinger11
      - RFinger12
      - RFinger13
      - LFinger21
      - LFinger22
      - LFinger23
      - RFinger21
      - RFinger22
      - RFinger23
      - LFinger31
      - LFinger32
      - LFinger33
      - RFinger31
      - RFinger32
      - RFinger33
      - LFinger41
      - LFinger42
      - LFinger43
      - RFinger41
      - RFinger42
      - RFinger43
      - LThumb1
      - RThumb1
      - LThumb2
      - RThumb2

