set(_AMENT_PACKAGE_NAME "pepper_robot")
set(pepper_robot_VERSION "1.0.0")
set(pepper_robot_MAINTAINER "Hiba Sekkat <h.sekkat@ueuromed.org>")
set(pepper_robot_BUILD_DEPENDS "pepper_robot_description" "pepper_robot_moveit_config" "xacro")
set(pepper_robot_BUILDTOOL_DEPENDS "ament_cmake")
set(pepper_robot_BUILD_EXPORT_DEPENDS )
set(pepper_robot_BUILDTOOL_EXPORT_DEPENDS )
set(pepper_robot_EXEC_DEPENDS )
set(pepper_robot_TEST_DEPENDS )
set(pepper_robot_GROUP_DEPENDS )
set(pepper_robot_MEMBER_OF_GROUPS )
set(pepper_robot_DEPRECATED "")
set(pepper_robot_EXPORT_TAGS)
list(APPEND pepper_robot_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
