set(_AMENT_PACKAGE_NAME "pepper_robot_moveit_config")
set(pepper_robot_moveit_config_VERSION "1.0.0")
set(pepper_robot_moveit_config_MAINTAINER "Andrej Orsula <andrejorsula@uni.lu>")
set(pepper_robot_moveit_config_BUILD_DEPENDS )
set(pepper_robot_moveit_config_BUILDTOOL_DEPENDS "ament_cmake")
set(pepper_robot_moveit_config_BUILD_EXPORT_DEPENDS )
set(pepper_robot_moveit_config_BUILDTOOL_EXPORT_DEPENDS )
set(pepper_robot_moveit_config_EXEC_DEPENDS "pepper_robot_description" "backward_ros" "control_msgs" "controller_manager" "hardware_interface" "ign_ros2_control" "joint_state_broadcaster" "joint_trajectory_controller" "moveit_ros_move_group" "moveit_servo" "moveit" "robot_state_publisher" "ros_ign_bridge" "ros_ign_gazebo" "rviz2" "urdf" "xacro")
set(pepper_robot_moveit_config_TEST_DEPENDS )
set(pepper_robot_moveit_config_GROUP_DEPENDS )
set(pepper_robot_moveit_config_MEMBER_OF_GROUPS )
set(pepper_robot_moveit_config_DEPRECATED "")
set(pepper_robot_moveit_config_EXPORT_TAGS)
list(APPEND pepper_robot_moveit_config_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
